name: Test
run-name: ${{ github.actor }} test
on: [pull_request_target, push]
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: ./scripts/script.sh
